FROM golang:1.24.6 AS builder
WORKDIR /app
COPY . .
RUN go mod tidy
RUN go build -o alert-service ./cmd/alert-service

FROM debian:bookworm-slim
WORKDIR /app
COPY --from=builder /app/alert-service .
EXPOSE 8080
CMD ["./alert-service"]
